#Banco de Dados para deploy
services:
  mysql_db:
    image: mysql:8.4.0-oraclelinux8
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db_data:/var/lib/mysql
  app:
    depends_on:
      - mysql_db
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/desafio-simplify
    container_name: desafio-simplify
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db_data:

#Banco de dados configurado para ser usado localmente
#services:
#  db:
#    image: mysql:8.4.0-oraclelinux8
#
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: mydb
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: admin
#
#    ports:
#      - "3306:3306"
#    expose:
#      - "3306"
#    volumes:
#      - db_data:/var/lib/mysql
#
#volumes:
#  db_data: